import { pgTable, serial, text, integer, boolean, jsonb } from 'drizzle-orm/pg-core';
import { categories } from './categories.js';

export const products = pgTable('products', {
  id: serial('id').primaryKey(),
  name: text('name').notNull(),
  category: text('category').references(() => categories.id).notNull(),
  subcategory: text('subcategory'),
  brand: text('brand'),
  sku: text('sku'),
  barcode: text('barcode'),
  weight: text('weight'),
  unit: text('unit'),
  packSize: text('pack_size'),
  price: integer('price').notNull(),
  mrp: integer('mrp'),
  costPrice: integer('cost_price').default(0),
  discount: integer('discount'),
  gstRate: integer('gst_rate').default(0),
  hsnCode: text('hsn_code'),
  batchNumber: text('batch_number'),
  mfgDate: text('mfg_date'),
  expiryDate: text('expiry_date'),
  image: text('image'),
  description: text('description'),
  inStock: boolean('in_stock').default(true),
  isArchived: boolean('is_archived').default(false),
  isPublished: boolean('is_published').default(true),
  deliveryTime: text('delivery_time').default('15 mins'),
  isBestseller: boolean('is_bestseller').default(false),
  isTodaysDeal: boolean('is_todays_deal').default(false),
  wholesalePrice: integer('wholesale_price'),
  bulkPackLabel: text('bulk_pack_label'),
  bulkPackPrice: integer('bulk_pack_price'),
  wholesaleCaseLabel: text('wholesale_case_label'),
  wholesaleCasePrice: integer('wholesale_case_price'),
  variants: jsonb('variants')
});
